kind: pipeline
name: install
steps:

- name: tags
  image: bitnami/git  # https://hub.docker.com/r/bitnami/git/
  commands:
  - git fetch --tags
  - echo "${SPIN}-$(git describe --tags --always --dirty)" > .tags

- name: publish
  image: plugins/docker # http://plugins.drone.io/drone-plugins/drone-docker/
  settings:
    dockerfile: Dockerfile.${SPIN}
    repo: "${CI_REPO}"
    tags:
    - '${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8},latest'
    username: digtux
    password:
      from_secret: dockerhub-pass

matrix:
  SPIN:
    - aline
    - kapitan

trigger:
  branch:
  - master
  - feature/*
  event:
  - push
  - tag
