apiVersion: v1
kind: Secret
metadata:
  name: laminar-config
  namespace: infra-laminar
data:
  id-rsa: <your_ssh_key_in_base64>
stringData:
  config.yaml: |
    ---
    global:
      gitUser: Laminar
      gitEmail: laminar@acme.org
      gitMessage: "automated promotion"

    dockerRegistries:
    - reg: 123123123123.dkr.ecr.eu-west-2.amazonaws.com/acmecorp
      name: ecr

    git:
    - name: ecr
      url: "git@github.com:acmecorp/my-kapitan-repo.git"
      branch: "develop"
      key: /config/id-rsa
      pollFreq: 60
      remoteConfig: true
      preCommitCommands:
      - "kapitan compile"
      - "sleep 3"
      - sync
      # this is because of a bug with go-git ignoring .gitignore, will be fixed soon aparently
      - "find . -type d -name __pycache__  -exec rm -rf {} +"


